# Generated by Django 3.0.3 on 2020-06-30 07:56

import advertise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(null=True, upload_to=advertise.models.upload_location)),
                ('page_size', models.CharField(choices=[('Half', 'half'), ('Quarter', 'quarter'), ('Full', 'full')], default='Half', max_length=15)),
                ('choose_place', models.CharField(choices=[('HomeTop', 'hometop'), ('HomeMiddle', 'homemiddle'), ('HomeBottom', 'homebottom'), ('HomeRight', 'homeright'), ('SingleTop', 'singletop'), ('SingleRight', 'singleright'), ('SingleBottom', 'singlebottom')], default='HomeTop', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
