# Generated by Django 3.0.3 on 2020-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
