# Generated by Django 3.0.3 on 2020-06-27 12:43

from django.db import migrations, models
import tenderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='org_add',
            new_name='org_address',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_type',
        ),
        migrations.AddField(
            model_name='tender',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=tenderapp.models.document_upload_location),
        ),
        migrations.AlterField(
            model_name='tender',
            name='published_on',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
