# Generated by Django 3.0.3 on 2020-07-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0004_auto_20200701_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(choices=[('Basic', 'basic'), ('Bulk', 'bulk'), ('Pro', 'pro')], default='Bulk', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('any_other_supply', models.CharField(blank=True, max_length=35, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
