# Generated by Django 3.0.3 on 2020-07-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0005_pricingclientinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingclientinfo',
            name='any_other_supply',
        ),
    ]
