# Generated by Django 3.0.3 on 2020-07-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0008_tender_allowed_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='allowed_memberships',
        ),
    ]
