# Generated by Django 3.0.3 on 2020-06-28 04:34

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('org_name', models.CharField(blank=True, max_length=50, null=True)),
                ('org_address', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('tender_description', models.TextField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to=auction.models.document_upload_location)),
                ('published_on', models.CharField(max_length=55, unique=True)),
                ('published_date', models.DateTimeField()),
                ('last_date', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=auction.models.upload_location)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
