# Generated by Django 3.0.3 on 2020-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='allowed_memberships',
            field=models.ManyToManyField(to='memberships.Membership'),
        ),
    ]
