# Generated by Django 3.0.3 on 2020-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200708_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FiveDays', 'fivedays'), ('Monthly', 'monthly'), ('TwoYears', 'twoyears'), ('FiveYears', 'fiveyears'), ('TenYears', 'tenyears'), ('Off', 'off')], default='FiveDays', max_length=30),
        ),
    ]
