# Generated by Django 3.0.3 on 2020-07-09 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_usermembership_membership_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='membership_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
