# Generated by Django 3.0.3 on 2020-07-09 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_usermembership_membership_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership_updated_at',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='membership_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
