# Generated by Django 3.0.3 on 2020-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20200709_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
